services:
  postgres:
    image: postgres:16-alpine
    container_name: ticket-sla-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    volumes:
      - ticket_sla_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  #TODO: need to change the default value env (example)
  app: 
    image: ticket-sla-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-sla-api
    ports:
      - "${APP_PORT}:${SERVER_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      WORKER_POOL_SIZE: ${WORKER_POOL_SIZE}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  ticket_sla_postgres_data: